// Full 78-card Tarot deck with numeric values
const TAROT_CARDS = [
  // Major Arcana (22 cards) - 0-21
  { name: "The Fool", value: 0 },
  { name: "The Magician", value: 1 },
  { name: "The High Priestess", value: 2 },
  { name: "The Empress", value: 3 },
  { name: "The Emperor", value: 4 },
  { name: "The Hierophant", value: 5 },
  { name: "The Lovers", value: 6 },
  { name: "The Chariot", value: 7 },
  { name: "Strength", value: 8 },
  { name: "The Hermit", value: 9 },
  { name: "Wheel of Fortune", value: 10 },
  { name: "Justice", value: 11 },
  { name: "The Hanged Man", value: 12 },
  { name: "Death", value: 13 },
  { name: "Temperance", value: 14 },
  { name: "The Devil", value: 15 },
  { name: "The Tower", value: 16 },
  { name: "The Star", value: 17 },
  { name: "The Moon", value: 18 },
  { name: "The Sun", value: 19 },
  { name: "Judgement", value: 20 },
  { name: "The World", value: 21 },

  // Minor Arcana - Wands (14 cards)
  { name: "Ace of Wands", value: 1 },
  { name: "Two of Wands", value: 2 },
  { name: "Three of Wands", value: 3 },
  { name: "Four of Wands", value: 4 },
  { name: "Five of Wands", value: 5 },
  { name: "Six of Wands", value: 6 },
  { name: "Seven of Wands", value: 7 },
  { name: "Eight of Wands", value: 8 },
  { name: "Nine of Wands", value: 9 },
  { name: "Ten of Wands", value: 10 },
  { name: "Page of Wands", value: 11 },
  { name: "Knight of Wands", value: 12 },
  { name: "Queen of Wands", value: 13 },
  { name: "King of Wands", value: 14 },

  // Minor Arcana - Cups (14 cards)
  { name: "Ace of Cups", value: 1 },
  { name: "Two of Cups", value: 2 },
  { name: "Three of Cups", value: 3 },
  { name: "Four of Cups", value: 4 },
  { name: "Five of Cups", value: 5 },
  { name: "Six of Cups", value: 6 },
  { name: "Seven of Cups", value: 7 },
  { name: "Eight of Cups", value: 8 },
  { name: "Nine of Cups", value: 9 },
  { name: "Ten of Cups", value: 10 },
  { name: "Page of Cups", value: 11 },
  { name: "Knight of Cups", value: 12 },
  { name: "Queen of Cups", value: 13 },
  { name: "King of Cups", value: 14 },

  // Minor Arcana - Swords (14 cards)
  { name: "Ace of Swords", value: 1 },
  { name: "Two of Swords", value: 2 },
  { name: "Three of Swords", value: 3 },
  { name: "Four of Swords", value: 4 },
  { name: "Five of Swords", value: 5 },
  { name: "Six of Swords", value: 6 },
  { name: "Seven of Swords", value: 7 },
  { name: "Eight of Swords", value: 8 },
  { name: "Nine of Swords", value: 9 },
  { name: "Ten of Swords", value: 10 },
  { name: "Page of Swords", value: 11 },
  { name: "Knight of Swords", value: 12 },
  { name: "Queen of Swords", value: 13 },
  { name: "King of Swords", value: 14 },

  // Minor Arcana - Pentacles (14 cards)
  { name: "Ace of Pentacles", value: 1 },
  { name: "Two of Pentacles", value: 2 },
  { name: "Three of Pentacles", value: 3 },
  { name: "Four of Pentacles", value: 4 },
  { name: "Five of Pentacles", value: 5 },
  { name: "Six of Pentacles", value: 6 },
  { name: "Seven of Pentacles", value: 7 },
  { name: "Eight of Pentacles", value: 8 },
  { name: "Nine of Pentacles", value: 9 },
  { name: "Ten of Pentacles", value: 10 },
  { name: "Page of Pentacles", value: 11 },
  { name: "Knight of Pentacles", value: 12 },
  { name: "Queen of Pentacles", value: 13 },
  { name: "King of Pentacles", value: 14 },
];

module.exports = { TAROT_CARDS };
