// Full 78-card Tarot deck with numbers
const TAROT_CARDS = [
  // Major Arcana (22 cards) - 0-21
  { name: "The Fool", number: 0, suit: "Major Arcana" },
  { name: "The Magician", number: 1, suit: "Major Arcana" },
  { name: "The High Priestess", number: 2, suit: "Major Arcana" },
  { name: "The Empress", number: 3, suit: "Major Arcana" },
  { name: "The Emperor", number: 4, suit: "Major Arcana" },
  { name: "The Hierophant", number: 5, suit: "Major Arcana" },
  { name: "The Lovers", number: 6, suit: "Major Arcana" },
  { name: "The Chariot", number: 7, suit: "Major Arcana" },
  { name: "Strength", number: 8, suit: "Major Arcana" },
  { name: "The Hermit", number: 9, suit: "Major Arcana" },
  { name: "Wheel of Fortune", number: 10, suit: "Major Arcana" },
  { name: "Justice", number: 11, suit: "Major Arcana" },
  { name: "The Hanged Man", number: 12, suit: "Major Arcana" },
  { name: "Death", number: 13, suit: "Major Arcana" },
  { name: "Temperance", number: 14, suit: "Major Arcana" },
  { name: "The Devil", number: 15, suit: "Major Arcana" },
  { name: "The Tower", number: 16, suit: "Major Arcana" },
  { name: "The Star", number: 17, suit: "Major Arcana" },
  { name: "The Moon", number: 18, suit: "Major Arcana" },
  { name: "The Sun", number: 19, suit: "Major Arcana" },
  { name: "Judgement", number: 20, suit: "Major Arcana" },
  { name: "The World", number: 21, suit: "Major Arcana" },

  // Minor Arcana - Wands (14 cards)
  { name: "Ace of Wands", number: 1, suit: "Wands" },
  { name: "Two of Wands", number: 2, suit: "Wands" },
  { name: "Three of Wands", number: 3, suit: "Wands" },
  { name: "Four of Wands", number: 4, suit: "Wands" },
  { name: "Five of Wands", number: 5, suit: "Wands" },
  { name: "Six of Wands", number: 6, suit: "Wands" },
  { name: "Seven of Wands", number: 7, suit: "Wands" },
  { name: "Eight of Wands", number: 8, suit: "Wands" },
  { name: "Nine of Wands", number: 9, suit: "Wands" },
  { name: "Ten of Wands", number: 10, suit: "Wands" },
  { name: "Page of Wands", number: 11, suit: "Wands" },
  { name: "Knight of Wands", number: 12, suit: "Wands" },
  { name: "Queen of Wands", number: 13, suit: "Wands" },
  { name: "King of Wands", number: 14, suit: "Wands" },

  // Minor Arcana - Cups (14 cards)
  { name: "Ace of Cups", number: 1, suit: "Cups" },
  { name: "Two of Cups", number: 2, suit: "Cups" },
  { name: "Three of Cups", number: 3, suit: "Cups" },
  { name: "Four of Cups", number: 4, suit: "Cups" },
  { name: "Five of Cups", number: 5, suit: "Cups" },
  { name: "Six of Cups", number: 6, suit: "Cups" },
  { name: "Seven of Cups", number: 7, suit: "Cups" },
  { name: "Eight of Cups", number: 8, suit: "Cups" },
  { name: "Nine of Cups", number: 9, suit: "Cups" },
  { name: "Ten of Cups", number: 10, suit: "Cups" },
  { name: "Page of Cups", number: 11, suit: "Cups" },
  { name: "Knight of Cups", number: 12, suit: "Cups" },
  { name: "Queen of Cups", number: 13, suit: "Cups" },
  { name: "King of Cups", number: 14, suit: "Cups" },

  // Minor Arcana - Swords (14 cards)
  { name: "Ace of Swords", number: 1, suit: "Swords" },
  { name: "Two of Swords", number: 2, suit: "Swords" },
  { name: "Three of Swords", number: 3, suit: "Swords" },
  { name: "Four of Swords", number: 4, suit: "Swords" },
  { name: "Five of Swords", number: 5, suit: "Swords" },
  { name: "Six of Swords", number: 6, suit: "Swords" },
  { name: "Seven of Swords", number: 7, suit: "Swords" },
  { name: "Eight of Swords", number: 8, suit: "Swords" },
  { name: "Nine of Swords", number: 9, suit: "Swords" },
  { name: "Ten of Swords", number: 10, suit: "Swords" },
  { name: "Page of Swords", number: 11, suit: "Swords" },
  { name: "Knight of Swords", number: 12, suit: "Swords" },
  { name: "Queen of Swords", number: 13, suit: "Swords" },
  { name: "King of Swords", number: 14, suit: "Swords" },

  // Minor Arcana - Pentacles (14 cards)
  { name: "Ace of Pentacles", number: 1, suit: "Pentacles" },
  { name: "Two of Pentacles", number: 2, suit: "Pentacles" },
  { name: "Three of Pentacles", number: 3, suit: "Pentacles" },
  { name: "Four of Pentacles", number: 4, suit: "Pentacles" },
  { name: "Five of Pentacles", number: 5, suit: "Pentacles" },
  { name: "Six of Pentacles", number: 6, suit: "Pentacles" },
  { name: "Seven of Pentacles", number: 7, suit: "Pentacles" },
  { name: "Eight of Pentacles", number: 8, suit: "Pentacles" },
  { name: "Nine of Pentacles", number: 9, suit: "Pentacles" },
  { name: "Ten of Pentacles", number: 10, suit: "Pentacles" },
  { name: "Page of Pentacles", number: 11, suit: "Pentacles" },
  { name: "Knight of Pentacles", number: 12, suit: "Pentacles" },
  { name: "Queen of Pentacles", number: 13, suit: "Pentacles" },
  { name: "King of Pentacles", number: 14, suit: "Pentacles" },
];

module.exports = { TAROT_CARDS };
