// Full 78-card Tarot deck with numeric values
const TAROT_CARDS = [
  // Major Arcana (22 cards) - 0-21
  { name: "The Fool", value: 0, suit: "Major Arcana" },
  { name: "The Magician", value: 1, suit: "Major Arcana" },
  { name: "The High Priestess", value: 2, suit: "Major Arcana" },
  { name: "The Empress", value: 3, suit: "Major Arcana" },
  { name: "The Emperor", value: 4, suit: "Major Arcana" },
  { name: "The Hierophant", value: 5, suit: "Major Arcana" },
  { name: "The Lovers", value: 6, suit: "Major Arcana" },
  { name: "The Chariot", value: 7, suit: "Major Arcana" },
  { name: "Strength", value: 8, suit: "Major Arcana" },
  { name: "The Hermit", value: 9, suit: "Major Arcana" },
  { name: "Wheel of Fortune", value: 10, suit: "Major Arcana" },
  { name: "Justice", value: 11, suit: "Major Arcana" },
  { name: "The Hanged Man", value: 12, suit: "Major Arcana" },
  { name: "Death", value: 13, suit: "Major Arcana" },
  { name: "Temperance", value: 14, suit: "Major Arcana" },
  { name: "The Devil", value: 15, suit: "Major Arcana" },
  { name: "The Tower", value: 16, suit: "Major Arcana" },
  { name: "The Star", value: 17, suit: "Major Arcana" },
  { name: "The Moon", value: 18, suit: "Major Arcana" },
  { name: "The Sun", value: 19, suit: "Major Arcana" },
  { name: "Judgement", value: 20, suit: "Major Arcana" },
  { name: "The World", value: 21, suit: "Major Arcana" },

  // Minor Arcana - Wands (14 cards)
  { name: "Ace of Wands", value: 1, suit: "Wands" },
  { name: "Two of Wands", value: 2, suit: "Wands" },
  { name: "Three of Wands", value: 3, suit: "Wands" },
  { name: "Four of Wands", value: 4, suit: "Wands" },
  { name: "Five of Wands", value: 5, suit: "Wands" },
  { name: "Six of Wands", value: 6, suit: "Wands" },
  { name: "Seven of Wands", value: 7, suit: "Wands" },
  { name: "Eight of Wands", value: 8, suit: "Wands" },
  { name: "Nine of Wands", value: 9, suit: "Wands" },
  { name: "Ten of Wands", value: 10, suit: "Wands" },
  { name: "Page of Wands", value: 11, suit: "Wands" },
  { name: "Knight of Wands", value: 12, suit: "Wands" },
  { name: "Queen of Wands", value: 13, suit: "Wands" },
  { name: "King of Wands", value: 14, suit: "Wands" },

  // Minor Arcana - Cups (14 cards)
  { name: "Ace of Cups", value: 1, suit: "Cups" },
  { name: "Two of Cups", value: 2, suit: "Cups" },
  { name: "Three of Cups", value: 3, suit: "Cups" },
  { name: "Four of Cups", value: 4, suit: "Cups" },
  { name: "Five of Cups", value: 5, suit: "Cups" },
  { name: "Six of Cups", value: 6, suit: "Cups" },
  { name: "Seven of Cups", value: 7, suit: "Cups" },
  { name: "Eight of Cups", value: 8, suit: "Cups" },
  { name: "Nine of Cups", value: 9, suit: "Cups" },
  { name: "Ten of Cups", value: 10, suit: "Cups" },
  { name: "Page of Cups", value: 11, suit: "Cups" },
  { name: "Knight of Cups", value: 12, suit: "Cups" },
  { name: "Queen of Cups", value: 13, suit: "Cups" },
  { name: "King of Cups", value: 14, suit: "Cups" },

  // Minor Arcana - Swords (14 cards)
  { name: "Ace of Swords", value: 1, suit: "Swords" },
  { name: "Two of Swords", value: 2, suit: "Swords" },
  { name: "Three of Swords", value: 3, suit: "Swords" },
  { name: "Four of Swords", value: 4, suit: "Swords" },
  { name: "Five of Swords", value: 5, suit: "Swords" },
  { name: "Six of Swords", value: 6, suit: "Swords" },
  { name: "Seven of Swords", value: 7, suit: "Swords" },
  { name: "Eight of Swords", value: 8, suit: "Swords" },
  { name: "Nine of Swords", value: 9, suit: "Swords" },
  { name: "Ten of Swords", value: 10, suit: "Swords" },
  { name: "Page of Swords", value: 11, suit: "Swords" },
  { name: "Knight of Swords", value: 12, suit: "Swords" },
  { name: "Queen of Swords", value: 13, suit: "Swords" },
  { name: "King of Swords", value: 14, suit: "Swords" },

  // Minor Arcana - Pentacles (14 cards)
  { name: "Ace of Pentacles", value: 1, suit: "Pentacles" },
  { name: "Two of Pentacles", value: 2, suit: "Pentacles" },
  { name: "Three of Pentacles", value: 3, suit: "Pentacles" },
  { name: "Four of Pentacles", value: 4, suit: "Pentacles" },
  { name: "Five of Pentacles", value: 5, suit: "Pentacles" },
  { name: "Six of Pentacles", value: 6, suit: "Pentacles" },
  { name: "Seven of Pentacles", value: 7, suit: "Pentacles" },
  { name: "Eight of Pentacles", value: 8, suit: "Pentacles" },
  { name: "Nine of Pentacles", value: 9, suit: "Pentacles" },
  { name: "Ten of Pentacles", value: 10, suit: "Pentacles" },
  { name: "Page of Pentacles", value: 11, suit: "Pentacles" },
  { name: "Knight of Pentacles", value: 12, suit: "Pentacles" },
  { name: "Queen of Pentacles", value: 13, suit: "Pentacles" },
  { name: "King of Pentacles", value: 14, suit: "Pentacles" },
];

module.exports = { TAROT_CARDS };
